package cn.banyingli.greendaodemo.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "CONCERT".
 */
@Entity
public class Concert {

    @Id
    private Long id;

    @NotNull
    private String title;

    @NotNull
    private String venue;

    @Generated
    public Concert() {
    }

    public Concert(Long id) {
        this.id = id;
    }

    @Generated
    public Concert(Long id, String title, String venue) {
        this.id = id;
        this.title = title;
        this.venue = venue;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    @NotNull
    public String getVenue() {
        return venue;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVenue(@NotNull String venue) {
        this.venue = venue;
    }

}
