package cn.banyingli.greendaodemo.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONCERT.
 */
public class Concert {

    private Long id;
    private Long concert_no;
    /** Not-null value. */
    private String title;
    private String venue;

    public Concert() {
    }

    public Concert(Long id, Long concert_no) {
        this.id = id;
        this.concert_no = concert_no;
    }

    public Concert(Long id, Long concert_no, String title, String venue) {
        this.id = id;
        this.concert_no = concert_no;
        this.title = title;
        this.venue = venue;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getConcert_no() {
        return concert_no;
    }

    public void setConcert_no(Long concert_no) {
        this.concert_no = concert_no;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getVenue() {
        return venue;
    }

    public void setVenue(String venue) {
        this.venue = venue;
    }

}
