package cn.banyingli.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.banyingli.greendaodemo.db.Concert;

import cn.banyingli.greendaodemo.db.ConcertDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig concertDaoConfig;

    private final ConcertDao concertDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        concertDaoConfig = daoConfigMap.get(ConcertDao.class).clone();
        concertDaoConfig.initIdentityScope(type);

        concertDao = new ConcertDao(concertDaoConfig, this);

        registerDao(Concert.class, concertDao);
    }
    
    public void clear() {
        concertDaoConfig.clearIdentityScope();
    }

    public ConcertDao getConcertDao() {
        return concertDao;
    }

}
