package cn.banyingli.greendaodemo.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cn.banyingli.greendaodemo.db.Concert;

import cn.banyingli.greendaodemo.db.ConcertDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig concertDaoConfig;

    private final ConcertDao concertDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        concertDaoConfig = daoConfigMap.get(ConcertDao.class).clone();
        concertDaoConfig.initIdentityScope(type);

        concertDao = new ConcertDao(concertDaoConfig, this);

        registerDao(Concert.class, concertDao);
    }
    
    public void clear() {
        concertDaoConfig.getIdentityScope().clear();
    }

    public ConcertDao getConcertDao() {
        return concertDao;
    }

}
